In [1]:
import numpy as np

In [2]:
# reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [3]:
# np.ones and np.zeros
# used for initialization
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# np.random
np.random.random((3,4))

array([[0.38178426, 0.07385818, 0.24066434, 0.14241233],
       [0.50602225, 0.95786781, 0.53757223, 0.43157683],
       [0.04210362, 0.717518  , 0.17195614, 0.61381238]])

In [6]:
# np.linspace(lower_range,upper_range,no.of items)
# linear spaced
# used in plotting graph within range
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [7]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [8]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [9]:
# vector 1d array
print(a1)

# matrix 2d array
print(a2)

# tensor 3d array
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [10]:
# ndim
# no. of dimensions
a2.ndim

2

In [11]:
# shape
a1.shape

(10,)

In [12]:
a2.shape

(3, 4)

In [13]:
a3.shape
# (how many 2d array,shape of 2d array)

(2, 2, 2)

In [14]:
# size
# no.of items
a1.size

10

In [15]:
a2.size

12

In [16]:
# itemsize
# size occupied by item in memory
a1.itemsize

8

In [17]:
a2.itemsize

8

In [18]:
# dtype
a1.dtype

dtype('int64')

# Changing Datatype

In [19]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations
### 1. Scaler operations
### 2. Vector operations

In [20]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [21]:
# scaler operations

# arithmetic
a1 **2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
# relational
a2 >15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
# vector operations
# arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Function

In [25]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[29.,  4., 11.],
       [67., 31., 13.],
       [89., 42., 88.]])

In [29]:
# min/max/sum/prod
np.min(a1)
np.sum(a1)
# 0-column and 1-row in axis
np.max(a1,axis=0)

array([89., 42., 88.])

In [30]:
#mean/std/median/var
np.mean(a1)

np.float64(41.55555555555556)

In [31]:
#trigonometric functions
np.sin(a1)

array([[-0.66363388, -0.7568025 , -0.99999021],
       [-0.85551998, -0.40403765,  0.42016704],
       [ 0.86006941, -0.91652155,  0.0353983 ]])

In [34]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [35]:
# log and exponents
np.exp(a1)

array([[3.93133430e+12, 5.45981500e+01, 5.98741417e+04],
       [1.25236317e+29, 2.90488497e+13, 4.42413392e+05],
       [4.48961282e+38, 1.73927494e+18, 1.65163625e+38]])

In [37]:
# round/floor/ceil
# ceil-- 6.1 ---7 and 6.5--7
# round--6.1--6 and 6.5--7
# floor --6.1--7 and 6.5--6

np.round(np.random.random((2,3))*100)

array([[16., 63., 47.],
       [57., 70., 56.]])

# Indexing and Slicing

In [38]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [39]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
# indexing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# negative indexing
a1[-1]

np.int64(9)

In [42]:
# positive indexing
a1[0]

np.int64(0)

In [43]:
# 2d array
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
# to fetch element 6, tell row ,then column

a2[1,2]

np.int64(6)

In [47]:
a2[2,3]

np.int64(11)

In [48]:
# 3d tensor
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [50]:
# fetching 5
# (Array no,row,col)
a3[1,0,1]
a3[0,0,0]

np.int64(0)

In [51]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a1[2:5]

array([2, 3, 4])

In [53]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a2[0,:]

array([0, 1, 2, 3])

In [55]:
a2[:,2]

array([ 2,  6, 10])

In [57]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [64]:
# fetch 1,3,9,11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [68]:
# fetch 4,7
a2[1,::3]

array([4, 7])

In [75]:
# fetch 1,2,3,5,6,7
a2[:2:,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [78]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [81]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
# fetch 3,4,5
a3[0,1]

array([3, 4, 5])

In [92]:
a3[1,:,1]

array([10, 13, 16])

In [93]:
# fetch 22,23,25,26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [94]:
a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
# fetch 0,2,18,20
a3[0::2,::3,::2]

array([[[ 0,  2]],

       [[18, 20]]])

## iterating


In [102]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [104]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


for i in np.nditer(a3):
    print(i)

# Reshaping

In [108]:
# reshape
# transpose
np.transpose(a2)
a2.T


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [110]:
# ravel --convert to 1d array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking and Splitting

In [113]:
# horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
print(a4)
print(a5)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [116]:
# horizontal stacking
b=np.hstack((a4,a5))


In [117]:
# vertical stacking
c=np.vstack((a4,a5))

In [119]:
# splitting
# horizontal split
np.hsplit(b,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [120]:
# vertical split
np.vsplit(c,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]